# Use the base image    
FROM amd64/debian:buster-slim
ENV DEBIAN_FRONTEND noninteractive

ARG VERSION=v1.0
ARG BUILD_NUMBER=0
ARG TARGETARCH

### COMMON
ADD frontend/quartus_22.1std.tgz /opt
ADD frontend/synopsys.tgz /usr
ADD frontend/vivado.tgz /tools
ADD frontend/quartus_13.tgz /opt
ADD frontend/oss-cad-suite-linux-amd64-20231005.tgz /tools
ADD backend/cadence.tgz /opt

RUN dpkg --add-architecture amd64 \
    && dpkg --add-architecture i386
RUN apt -y update && apt -y upgrade
RUN apt install -y \
    lxde-core \
    xfce4-terminal

# Install required packages for RDP
RUN apt install -y sudo wget xorgxrdp xrdp \
    && apt remove -y light-locker xscreensaver \
    && apt autoremove -y

# Install VNC, SSH
RUN apt install -y --no-install-recommends x11vnc xvfb openssh-server novnc python3-websockify
RUN echo 'PermitRootLogin Yes' >> /etc/ssh/sshd_config \
    && echo 'X11Forwarding yes' >> /etc/ssh/sshd_config \
    && echo 'X11DisplayOffset 10' >> /etc/ssh/sshd_config \
    && echo 'X11UseLocalhost no' >> /etc/ssh/sshd_config

RUN apt install -y --no-install-recommends gcc make libc6-dev g++

# Install Firefox
RUN apt install -y firefox-esr

# Install additional utilities and locales
RUN echo "export TZ=Asia/Ho_Chi_Minh" > /etc/profile.d/env.sh
RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
RUN apt install -y htop nano vim neovim tree locales mousepad git xterm tcl yad environment-modules 

### INSTALL QUARTUS
# Install dependencies
RUN apt install -y libc6:amd64 libglib2.0-0:amd64 libfontconfig1:amd64 libx11-xcb1:amd64 libxext6:amd64 libsm6:amd64 libdbus-1-3:amd64 libxft2:amd64

# Configure Quartus settings
RUN mkdir /root/.altera.quartus
RUN echo "[General 22.1]" > /root/.altera.quartus/quartus2.ini \
    && echo "LICENSE_FILE = LM_LICENSE_FILE" >> /root/.altera.quartus/quartus2.ini

### INSTALL SYNOPSYS
RUN mkdir -p /usr/local/flexlm/licenses/ \
    && mkdir -p /usr/tmp/.flexlm

# Install dependencies
RUN apt install -y libncurses5:amd64 libmng1:amd64 csh dc \
    libstdc++6:amd64 libxss1:amd64 libxt6:amd64 libxmu6:amd64 libnuma1:amd64 libxi6:amd64 libxrandr2:amd64 libtiff5:amd64 libgl1:amd64

# Copy Synopsys license file and daemons
COPY frontend/license.dat /usr/local/flexlm/licenses
COPY frontend/daemons/mgcld /usr/synopsys/11.9/amd64/bin
COPY frontend/libpng12.so.0.54.0 /usr/lib

# Create a symbolic links
RUN ln -s /usr/lib/libpng12.so.0.54.0 /usr/lib/libpng12.so.0 \
    && ln -s /lib64/ld-linux-x86-64.so.2 /lib64/ld-lsb-x86-64.so.3 \
    && ln -s /usr/lib/x86_64-linux-gnu/libtiff.so.5 /usr/lib/x86_64-linux-gnu/libtiff.so.3

# Patches
RUN mv /usr/synopsys/cx-K-2015.06/platforms/linux64/lib/libstdc++.so.6 /usr/synopsys/cx-K-2015.06/platforms/linux64/lib/libstdc++.so.6_bak \
    && ln -s /usr/lib/x86_64-linux-gnu/libstdc++.so.6 /usr/synopsys/cx-K-2015.06/platforms/linux64/lib/libstdc++.so.6 \
    && mv /usr/synopsys/vc_static-O-2018.09-SP2-2/verdi/etc/lib/libstdc++/LINUXAMD64/libtinfo.so.5 /usr/synopsys/vc_static-O-2018.09-SP2-2/verdi/etc/lib/libstdc++/LINUXAMD64/libtinfo.so.5_bak \
    && ln -s c /usr/synopsys/vc_static-O-2018.09-SP2-2/verdi/etc/lib/libstdc++/LINUXAMD64/libtinfo.so.5

# Set bash as the default shell
RUN rm -f /usr/bin/sh && ln -s /usr/bin/bash /usr/bin/sh \
    && rm -f /bin/sh && ln -s /bin/bash /bin/sh

### INSTALL VIVADO
RUN apt install -y libtinfo5:amd64 libxtst6:amd64 libasound2:amd64 libcom-err2:amd64 libkeyutils1:amd64 libpulse0:amd64 libqt5webenginewidgets5:amd64

### INSTALL QUARTUS 13
RUN apt install -y libc6:i386 libx11-6:i386 libxext6:i386 libxft2:i386 libncurses5:i386 libsm6:i386

### INSTALL CADENCE
RUN apt install -y ksh csh libc6-amd64 evince

COPY backend/cadence_vco.sh /opt/mentor/calibre2015/aoi_cal_2015.2_36.27/pkgs/calibre_base/bin/calibre_vco
COPY backend/cadence_vco.sh /opt/mentor/calibre2015/aoi_cal_2015.2_36.27/pkgs/calibre_base.aoi/bin/calibre_vco

RUN chmod +x /opt/mentor/calibre2015/aoi_cal_2015.2_36.27/pkgs/calibre_base/bin/calibre_vco /opt/mentor/calibre2015/aoi_cal_2015.2_36.27/pkgs/calibre_base.aoi/bin/calibre_vco

######### FINALIZE
# Add modules
COPY frontend/modules /usr/share/modules/modulefiles
COPY backend/modules /usr/share/modules/modulefiles

# Add Desktop shortcuts
RUN mkdir /root/Desktop
COPY Desktop/* /root/Desktop/
COPY frontend/Desktop/* /root/Desktop/
COPY backend/Desktop/* /root/Desktop/
RUN find /root/Desktop -type f -exec chmod +x {} \; 

# Create symbolic links for shared folders
RUN mkdir /media/share \
    && ln -s /media/share /root/Desktop/Share \
    && ln -s /media/share /root/Share

# PCMAN bypass asking for execute
RUN mkdir -p /root/.config/libfm
RUN echo '[config]' > /root/.config/libfm/libfm.conf \
    && echo 'quick_exec = 1' >> /root/.config/libfm/libfm.conf

# Unlimited Scroll for XFCE Terminal
RUN mkdir -p /root/.config/xfce4/terminal
RUN echo '[Configuration]' > /root/.config/xfce4/terminal/terminalrc \
    && echo 'ScrollingUnlimited=TRUE' >> /root/.config/xfce4/terminal/terminalrc

# Add info.sh
COPY info /bin
COPY info_autostart.desktop /etc/xdg/autostart
RUN chmod +x /bin/info

RUN sed -i "s/;;VERSION/$VERSION/" /bin/info \
    && sed -i "s/;;BUILD_NUMBER/$BUILD_NUMBER/" /bin/info \
    && sed -i 's/;;BuiltAt/TXT+="\\tBuilt at `date`\\n\\n"/g' /bin/info

# Copy a custom script and set it as the entry point
COPY ./run.sh /usr/bin/run.sh
RUN chmod +x /usr/bin/run.sh

# Set the root password
RUN echo 'root:toor' | chpasswd

# Remove apt caches and /tmp
RUN rm -rf /var/cache/apt /var/lib/apt/lists
RUN rm -rf /tmp/*

## This stage is used on mac"
RUN if [ "${TARGETARCH}" = "mac" ]; then \
        echo "TARGETARCH = mac"; \
    ## This stage is used on amd64"
    else \ 
        sed -i '/-XX:ActiveProcessorCount=2/d' /opt/intelFPGA/22.1std/nios2eds/bin/eclipse_nios2/eclipse.ini; \
        sed -i 's/taskset -c 0-3 //' /root/Desktop/Vivado2023.1.desktop; \
        sed -i 's/taskset -c 4-7 //' /root/Desktop/VitisHLS2023.1.desktop; \
        sed -i 's/taskset -c 0-3 //' /root/Desktop/Quartus.desktop; \
        sed -i 's/taskset -c 0-3 //' /usr/share/modules/modulefiles/vivado; \
        sed -i 's/taskset -c 4-7 //' /usr/share/modules/modulefiles/vivado; \
        sed -i 's/taskset -c 0-3 //' /usr/share/modules/modulefiles/quartus/22.1std; \
        sed -i 's|Exec=/opt/altera/13.0sp1/quartus/bin/quartus|Exec=/opt/altera/13.0sp1/quartus/bin/quartus --64bit|' /root/Desktop/QuartusII.desktop; \
        sed -i 's/(32-bit)/(64-bit)/g' /root/Desktop/QuartusII.desktop; \
        echo 'set-alias quartus "quartus --64bit"' >> /usr/share/modules/modulefiles/quartus/13.0sp1; \
        sed -i 's/Apple Silicon Macs/x86_64 machines/' /bin/info; \
    fi

# Docker config
EXPOSE 3389
ENTRYPOINT ["/usr/bin/run.sh"]