# Use the base image    
FROM amd64/debian:buster-20230919-slim
ENV DEBIAN_FRONTEND noninteractive

### COMMON
ADD frontend/quartus_22.1std.tgz /opt
ADD frontend/synopsys.tgz /usr
ADD frontend/vivado.tgz /tools
ADD frontend/quartus_13.tgz /opt
ADD frontend/oss-cad-suite-linux-amd64-20231005.tgz /tools
ADD backend/cadence.tgz /opt
ADD frontend/eds.tgz /opt/intelFPGA

RUN dpkg --add-architecture amd64 \
    && dpkg --add-architecture i386
RUN apt -y update && apt -y upgrade
RUN apt install -y --no-install-recommends lxde-core xfce4-terminal

# Install required packages for RDP
RUN apt install -y wget xorgxrdp xrdp \
    && apt remove -y light-locker xscreensaver \
    && apt autoremove -y

# Install VNC, SSH
RUN apt install -y --no-install-recommends x11vnc xvfb openssh-server novnc python3-websockify
RUN echo 'PermitRootLogin Yes' >> /etc/ssh/sshd_config \
    && echo 'X11Forwarding yes' >> /etc/ssh/sshd_config \
    && echo 'X11DisplayOffset 10' >> /etc/ssh/sshd_config \
    && echo 'X11UseLocalhost no' >> /etc/ssh/sshd_config

RUN apt install -y --no-install-recommends gcc cmake make libc6-dev g++

# Install additional utilities and locales
RUN echo "export TZ=Asia/Ho_Chi_Minh" > /etc/profile.d/env.sh
RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
RUN apt install -y --no-install-recommends htop nano vim neovim tree locales mousepad git xterm tcl yad environment-modules firefox-esr

### INSTALL QUARTUS
# Install dependencies
RUN apt install -y libc6 libglib2.0-0 libfontconfig1 libx11-xcb1 libxext6 libsm6 libdbus-1-3 libxft2 libpython3.7

# Configure Quartus settings
RUN mkdir /root/.altera.quartus
RUN echo "[General 22.1]" > /root/.altera.quartus/quartus2.ini \
    && echo "LICENSE_FILE = LM_LICENSE_FILE" >> /root/.altera.quartus/quartus2.ini

### INSTALL SYNOPSYS
RUN mkdir -p /usr/local/flexlm/licenses/ \
    && mkdir -p /usr/tmp/.flexlm

# Install dependencies
RUN apt install -y libncurses5 libmng1 csh dc \
    libstdc++6 libxss1 libxt6 libxmu6 libnuma1 libxi6 libxrandr2 libtiff5 libgl1

# Copy Synopsys license file and daemons
COPY frontend/license.dat /usr/local/flexlm/licenses
COPY frontend/daemons/mgcld /usr/synopsys/11.9/amd64/bin
COPY frontend/libpng12.so.0.54.0 /usr/lib

# Create a symbolic links
RUN ln -s /usr/lib/libpng12.so.0.54.0 /usr/lib/libpng12.so.0 \
    && ln -s /lib64/ld-linux-x86-64.so.2 /lib64/ld-lsb-x86-64.so.3 \
    && ln -s /usr/lib/x86_64-linux-gnu/libtiff.so.5 /usr/lib/x86_64-linux-gnu/libtiff.so.3

# Patches
RUN mv /usr/synopsys/cx-K-2015.06/platforms/linux64/lib/libstdc++.so.6 /usr/synopsys/cx-K-2015.06/platforms/linux64/lib/libstdc++.so.6_bak \
    && ln -s /usr/lib/x86_64-linux-gnu/libstdc++.so.6 /usr/synopsys/cx-K-2015.06/platforms/linux64/lib/libstdc++.so.6 \
    && mv /usr/synopsys/vc_static-O-2018.09-SP2-2/verdi/etc/lib/libstdc++/LINUXAMD64/libtinfo.so.5 /usr/synopsys/vc_static-O-2018.09-SP2-2/verdi/etc/lib/libstdc++/LINUXAMD64/libtinfo.so.5_bak \
    && ln -s c /usr/synopsys/vc_static-O-2018.09-SP2-2/verdi/etc/lib/libstdc++/LINUXAMD64/libtinfo.so.5

# Set bash as the default shell
RUN rm -f /usr/bin/sh && ln -s /usr/bin/bash /usr/bin/sh \
    && rm -f /bin/sh && ln -s /bin/bash /bin/sh

### INSTALL VIVADO
RUN apt install -y libtinfo5 libxtst6 libasound2 libcom-err2 libkeyutils1 libpulse0 libqt5webenginewidgets5

### INSTALL QUARTUS 13
RUN apt install -y libc6:i386 libx11-6:i386 libxext6:i386 libxft2:i386 libncurses5:i386 libsm6:i386 libxtst6:i386

ARG TARGETARCH
RUN if [ "${TARGETARCH}" = "mac" ]; then \
        ## PATCH QUARTUS13
        dpkg --add-architecture arm64; \
        apt update; \
        apt install -y qemu:arm64 binfmt-support:arm64 qemu-user-static:arm64; \
        echo 'export CMD_NAME=`basename $0`; set -f; export cmd_line=""; for cmd in "$@"; do if test "$cmd" = "--64bit"; then export QUARTUS_64BIT=1; else cmd_line="$cmd_line \"$cmd\""; fi; done; eval exec "qemu-x86_64-static $(dirname $(which $CMD_NAME))/../linux64/$CMD_NAME $cmd_line"' > /opt/altera/13.0sp1/quartus/linux/quartus && chmod +x opt/altera/13.0sp1/quartus/linux/quartus; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus /opt/altera/13.0sp1/quartus/linux/quartus_map; \       
        cp /opt/altera/13.0sp1/quartus/linux/quartus /opt/altera/13.0sp1/quartus/linux/quartus_fit; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus /opt/altera/13.0sp1/quartus/linux/quartus_pow; \
        echo 'export CMD_NAME=`basename $0`; set -f; export cmd_line=""; for cmd in "$@"; do if test "$cmd" = "--64bit"; then export QUARTUS_64BIT=1; else cmd_line="$cmd_line \"$cmd\""; fi; done; eval exec "$(dirname $(which $CMD_NAME))/../linux64/$CMD_NAME $cmd_line"' > /opt/altera/13.0sp1/quartus/linux/quartus_asm && chmod +x opt/altera/13.0sp1/quartus/linux/quartus_asm; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/quartus_sta; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/quartus_sh; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/quartus_eda; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/quartus_pgm; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/quartus_pgmw; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/mif2hex; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/alterad; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/altgx_diffmifgen; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/pll_cmd; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/quartus_fid; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/mega_lpm_divideq; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/xcvr_diffmifgen; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/mega_altdqsq; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/jtagconfig; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/altgx_mifgen; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/mega_alteccq; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/mega_altiobufq; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/mega_altparallel_flash_loaderq; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/gnuplot; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/mega_altgxbq; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/lmutil; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/mega_altfp_sqrtq; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/mega_altfp_compareq; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/mega_lpm_muxq; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/mega_altmemmultq; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/quartus_hps; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/wish; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/tb2_sender; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/mega_altfp_sincosq; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/mega_lpm_multq; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/mega_altfp_add_subq; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/quartus_si; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/qwedt; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/fir_netlist_writer; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/quartus_fitw; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/qred; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/qwed; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/qt_example_app; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/mega_altmult_addq; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/mega_altsource_probeq; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/quartus_npp; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/dmf_ver; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/quartus_cdb; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/quartus_cpf; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/tb2_install; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/qemit; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/mega_altfp_atanq; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/qatc; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/mega_lpm_shiftregq; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/mega_lpm_counterq; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/quartus_cmd; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/qeslc; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/quartus_cvp; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/mega_altpll_reconfigq; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/clearbox; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/qmegawiz; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/mega_altint_oscq; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/mega_lpm_decodeq; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/mega_altsld_virtual_jtagq; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/mega_lpm_add_subq; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/mega_csmq; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/qreg; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/qppl; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/mega_sld_signaltapq; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/mega_lpm_clshiftq; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/quartus_jli; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/mega_alt2gxb_reconfigq; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/mega_altshift_tapsq; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/quartus_sim; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/qmegawizq; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/lmgrd; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/mega_altclkbufq; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/jtagd; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/quartus_jbcc; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/mega_alt_octq; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/qfid; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/quartus_drc; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/mega_altremote_updateq; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/mega_ramq; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/mega_lpm_compareq; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/quartus_stpw; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/uniphy_mcc; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/quartus_rpp; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/qbnl; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/mega_symc; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/mega_altsqrtq; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/mega_altserial_flash_loaderq; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/qpgmt; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/mega_alt_fault_injection; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/qsme; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/quartus_staw; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/mega_symcng; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/qnui; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/tclsh; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/mega_altfp_divq; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/mega_parallel_addq; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/mega_altpllq; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/quartus_stp; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/mw-regenerate; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/mega_lpm_constq; \
        cp /opt/altera/13.0sp1/quartus/linux/quartus_asm /opt/altera/13.0sp1/quartus/linux/cbx_altfpc; \
    fi

# INSTALL oss-cad-suite
RUN apt install -y zlib1g-dev ghostscript

### INSTALL CADENCE
RUN apt install -y ksh csh libc6-amd64 evince psmisc

# Patches
RUN ln -s /usr/lib/x86_64-linux-gnu /usr/lib64 \
    && ln -s /usr/lib/libchm.so.1 /usr/lib/libchm.so \
    && ln -s /usr/bin/gcc /opt/cadence/MMSIM151/tools.lnx86/cdsgcc/gcc/4.8/bin/gcc_sys \
    && mv /opt/cadence/MMSIM151/tools.lnx86/cdsgcc/gcc/4.8/bin/g++ /opt/cadence/MMSIM151/tools.lnx86/cdsgcc/gcc/4.8/bin/g++_bak \
    && ln -s /opt/cadence/MMSIM151/tools.lnx86/cdsgcc/gcc/4.8/bin/gcc_sys /opt/cadence/MMSIM151/tools.lnx86/cdsgcc/gcc/4.8/bin/g++

COPY backend/cadence_vco.sh /opt/mentor/calibre2015/aoi_cal_2015.2_36.27/pkgs/calibre_base/bin/calibre_vco
COPY backend/cadence_vco.sh /opt/mentor/calibre2015/aoi_cal_2015.2_36.27/pkgs/calibre_base.aoi/bin/calibre_vco

RUN chmod +x /opt/mentor/calibre2015/aoi_cal_2015.2_36.27/pkgs/calibre_base/bin/calibre_vco /opt/mentor/calibre2015/aoi_cal_2015.2_36.27/pkgs/calibre_base.aoi/bin/calibre_vco

# Install PDKs
ADD backend/PDKs/gpdk045.tgz /opt/PDKs
ADD backend/PDKs/FreePDK45.tgz /opt/PDKs
ADD backend/PDKs/FreePDK15.tgz /opt/PDKs
ADD backend/PDKs/cdk160.tgz /opt/PDKs
ADD backend/PDKs/tsmc13.tgz /opt/PDKs
ADD backend/PDKs/tsmc18.tgz /opt/PDKs
ADD backend/PDKs/TSMCn65.tgz /opt/PDKs
ADD backend/PDKs/Full_Flow_Lab_Lib_TSMC180_New.tgz /opt/PDKs
COPY backend/PDKs/cds.lib /opt/cadence/IC617/share/cdssetup/cds.lib
# Patch FreePDK45
RUN sed -i 's/\$PDK_DIR/\/opt\/PDKs\/FreePDK45/g; /^[[:blank:]]*$/!s/$/'\''/' /opt/PDKs/FreePDK45/ncsu_basekit/models/hspice/hspice_nom.include

######### FINALIZE
# Ultilities
RUN apt install -y gpicview xarchiver iputils-ping clang

# Install VSCode (amd64) only
RUN if [ "${TARGETARCH}" = "amd64" ]; then \
        apt install -y wget gpg; \
        wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg; \
        install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg; \
        sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'; \
        rm -f packages.microsoft.gpg; \
        apt install apt-transport-https && apt update; \
        apt install -y code; \
    fi

# Add modules
COPY frontend/modules /usr/share/modules/modulefiles
COPY backend/modules /usr/share/modules/modulefiles

# Add Desktop shortcuts
RUN mkdir /root/Desktop
COPY Desktop/* /root/Desktop/
COPY frontend/Desktop/* /root/Desktop/
COPY backend/Desktop/* /root/Desktop/
RUN cp /usr/share/applications/code.desktop /root/Desktop/ 2>/dev/null || :
RUN find /root/Desktop -type f -exec chmod +x {} \;

# Create symbolic links for shared folders
RUN mkdir /media/share \
    && ln -s /media/share /root/Desktop/Share \
    && ln -s /media/share /root/Share

# PCMAN bypass asking for execute
RUN mkdir -p /root/.config/libfm
RUN echo '[config]' > /root/.config/libfm/libfm.conf \
    && echo 'quick_exec = 1' >> /root/.config/libfm/libfm.conf

# Unlimited Scroll for XFCE Terminal
RUN mkdir -p /root/.config/xfce4/terminal
RUN echo '[Configuration]' > /root/.config/xfce4/terminal/terminalrc \
    && echo 'ScrollingUnlimited=TRUE' >> /root/.config/xfce4/terminal/terminalrc

ARG VERSION=v1.0
ARG BUILD_NUMBER=0

# Add info.sh
COPY info /bin
COPY info_autostart.desktop /etc/xdg/autostart
RUN chmod +x /bin/info

RUN sed -i "s/;;VERSION/$VERSION/" /bin/info \
    && sed -i "s/;;BUILD_NUMBER/$BUILD_NUMBER/" /bin/info \
    && sed -i "s/;;BuiltAt/TXT+=\"\\\tBuilt at $(date)\\\n\\\n\"/g" /bin/info

# Copy a custom script and set it as the entry point
COPY ./run.sh /usr/bin/run.sh
RUN chmod +x /usr/bin/run.sh

# Set the root password
RUN echo 'root:toor' | chpasswd

## This stage is used on mac"
RUN if [ "${TARGETARCH}" = "mac" ]; then \
        echo "prepend-path PATH /opt/altera/13.0sp1/quartus/linux" | tee -a /usr/share/modules/modulefiles/quartus/13.0sp1; \
    ## This stage is used on amd64"
    else \ 
        sed -i '/-XX:ActiveProcessorCount=2/d' /opt/intelFPGA/22.1std/nios2eds/bin/eclipse_nios2/eclipse.ini; \
        sed -i 's/taskset -c 0-3 //' /root/Desktop/Vivado2023.1.desktop; \
        sed -i 's/taskset -c 4-7 //' /root/Desktop/VitisHLS2023.1.desktop; \
        sed -i 's/taskset -c 0-3 //' /root/Desktop/Quartus.desktop; \
        sed -i 's/taskset -c 0-3 //' /usr/share/modules/modulefiles/vivado; \
        sed -i 's/taskset -c 4-7 //' /usr/share/modules/modulefiles/vivado; \
        sed -i 's/taskset -c 0-3 //' /usr/share/modules/modulefiles/quartus/22.1std; \
        sed -i 's/Exec=\/bin\/bash -c "module load quartus\/13.0sp1 \&\& quartus"/Exec=\/bin\/bash -c "module load quartus\/13.0sp1 \&\& quartus --64bit"/' /root/Desktop/QuartusII.desktop; \
        sed -i 's/Exec=\/bin\/bash -c "module load quartus\/13.0sp1 \&\& quartus_pgmw"/Exec=\/bin\/bash -c "module load quartus\/13.0sp1 \&\& quartus_pgmw --64bit"/' /root/Desktop/QuartusII.desktop; \
        # sed -i 's/(32-bit)/(64-bit)/g' /root/Desktop/QuartusII.desktop; \
        # echo 'set-alias quartus "quartus --64bit"' >> /usr/share/modules/modulefiles/quartus/13.0sp1; \
        sed -i 's/Apple Silicon Macs/x86_64 machines/' /bin/info; \
    fi

# Add script for create user
COPY newuser /bin
RUN chmod +x /bin/newuser

# Remove apt caches and /tmp
RUN rm -rf /var/cache/apt /var/lib/apt/lists
RUN rm -rf /tmp/*

# Docker config
EXPOSE 3389
ENTRYPOINT ["/usr/bin/run.sh"]