# Use the base image    
FROM amd64/debian:buster-20230919-slim
#FROM amd64/debian:buster
ENV DEBIAN_FRONTEND noninteractive

### COMMON
ADD frontend/vivado.tgz /tools

RUN dpkg --add-architecture amd64 \
    && dpkg --add-architecture i386
RUN apt -y update && apt -y upgrade
RUN apt install -y --no-install-recommends lxde-core xfce4-terminal

# Install required packages for RDP
RUN apt install -y wget xorgxrdp xrdp \
    && apt remove -y light-locker xscreensaver \
    && apt autoremove -y

# Install VNC, SSH
RUN apt install -y --no-install-recommends x11vnc xvfb openssh-server novnc python3-websockify
RUN echo 'PermitRootLogin Yes' >> /etc/ssh/sshd_config \
    && echo 'X11Forwarding yes' >> /etc/ssh/sshd_config \
    && echo 'X11DisplayOffset 10' >> /etc/ssh/sshd_config \
    && echo 'X11UseLocalhost no' >> /etc/ssh/sshd_config

RUN apt install -y --no-install-recommends gcc cmake make libc6-dev g++

# Install additional utilities and locales
RUN echo "export TZ=Asia/Ho_Chi_Minh" > /etc/profile.d/env.sh
RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
RUN apt install -y --no-install-recommends htop nano vim neovim tree locales mousepad git xterm tcl yad environment-modules firefox-esr

# Set bash as the default shell
RUN rm -f /usr/bin/sh && ln -s /usr/bin/bash /usr/bin/sh \
    && rm -f /bin/sh && ln -s /bin/bash /bin/sh

### INSTALL VIVADO
RUN apt install -y libtinfo5 libxtst6 libasound2 libcom-err2 libkeyutils1 libpulse0 libqt5webenginewidgets5
RUN mkdir /root/.Xilinx        
COPY frontend/license.lic /root/.Xilinx

# Add modules
COPY frontend/modules /usr/share/modules/modulefiles
COPY backend/modules /usr/share/modules/modulefiles

# Add Desktop shortcuts
RUN mkdir /root/Desktop
COPY Desktop/* /root/Desktop/
COPY frontend/Desktop/* /root/Desktop/
COPY backend/Desktop/* /root/Desktop/
RUN cp /usr/share/applications/code.desktop /root/Desktop/ 2>/dev/null || :
RUN find /root/Desktop -type f -exec chmod +x {} \;

# Create symbolic links for shared folders
RUN mkdir /media/share \
    && ln -s /media/share /root/Desktop/Share \
    && ln -s /media/share /root/Share

# PCMAN bypass asking for execute
RUN mkdir -p /root/.config/libfm
RUN echo '[config]' > /root/.config/libfm/libfm.conf \
    && echo 'quick_exec = 1' >> /root/.config/libfm/libfm.conf

# Unlimited Scroll for XFCE Terminal
RUN mkdir -p /root/.config/xfce4/terminal
RUN echo '[Configuration]' > /root/.config/xfce4/terminal/terminalrc \
    && echo 'ScrollingUnlimited=TRUE' >> /root/.config/xfce4/terminal/terminalrc

ARG VERSION=v1.0
ARG BUILD_NUMBER=0

# Add info.sh
COPY info /bin
COPY info_autostart.desktop /etc/xdg/autostart
RUN chmod +x /bin/info

RUN sed -i "s/;;VERSION/$VERSION/" /bin/info \
    && sed -i "s/;;BUILD_NUMBER/$BUILD_NUMBER/" /bin/info \
    && sed -i "s/;;BuiltAt/TXT+=\"\\\tBuilt at $(date)\\\n\\\n\"/g" /bin/info

# Copy a custom script and set it as the entry point
COPY ./run.sh /usr/bin/run.sh
RUN chmod +x /usr/bin/run.sh

# Set the root password
RUN echo 'root:toor' | chpasswd

## This stage is used on mac"
RUN if [ "${TARGETARCH}" = "mac" ]; then \
        echo "prepend-path PATH /opt/altera/13.0sp1/quartus/linux" | tee -a /usr/share/modules/modulefiles/quartus/13.0sp1; \
    ## This stage is used on amd64"
    else \ 
        sed -i '/-XX:ActiveProcessorCount=2/d' /opt/intelFPGA/22.1std/nios2eds/bin/eclipse_nios2/eclipse.ini; \
        sed -i 's/taskset -c 0-3 //' /root/Desktop/Vivado2023.1.desktop; \
        sed -i 's/taskset -c 4-7 //' /root/Desktop/VitisHLS2023.1.desktop; \
        sed -i 's/taskset -c 0-3 //' /root/Desktop/Quartus.desktop; \
        sed -i 's/taskset -c 0-3 //' /usr/share/modules/modulefiles/vivado; \
        sed -i 's/taskset -c 4-7 //' /usr/share/modules/modulefiles/vivado; \
        sed -i 's/taskset -c 0-3 //' /usr/share/modules/modulefiles/quartus/22.1std; \
        sed -i 's/Exec=\/bin\/bash -c "module load quartus\/13.0sp1 \&\& quartus"/Exec=\/bin\/bash -c "module load quartus\/13.0sp1 \&\& quartus --64bit"/' /root/Desktop/QuartusII.desktop; \
        sed -i 's/Exec=\/bin\/bash -c "module load quartus\/13.0sp1 \&\& quartus_pgmw"/Exec=\/bin\/bash -c "module load quartus\/13.0sp1 \&\& quartus_pgmw --64bit"/' /root/Desktop/QuartusII.desktop; \
        # sed -i 's/(32-bit)/(64-bit)/g' /root/Desktop/QuartusII.desktop; \
        # echo 'set-alias quartus "quartus --64bit"' >> /usr/share/modules/modulefiles/quartus/13.0sp1; \
        sed -i 's/Apple Silicon Macs/x86_64 machines/' /bin/info; \
    fi

# Add script for create user
COPY newuser /bin
RUN chmod +x /bin/newuser

# Remove apt caches and /tmp
RUN rm -rf /var/cache/apt /var/lib/apt/lists
RUN rm -rf /tmp/*

# Docker config
EXPOSE 3389
ENTRYPOINT ["/usr/bin/run.sh"]
