#!/bin/bash

KEY=$RANDOM

updatenotes="v1.00 - 190923: Init version
v1.01 - 200923: Fixed hostname, any hostname is ok
v1.02 - 200923: Added Firefox (bc Chromium is very slow)
v1.10 - 210923: Added modules, Quartus II (launch ModelSim from Quartus not working)
v1.15 - 220923: Added info GUI (auto start)
v1.20 - 230923: Added support for x86_64 machines (add 'amd64' when running the container)
v1.21 - 230923: Added vim, nvim
v1.25 - 250923: Added ssh, vnc
v1.26 - 021023: Updated ModelSim 18.1 to fix Itcl issue; Unlimited scroll for XFCE Terminal
v1.30 - 061023: Updated multi-arch images
v2.00 - 081023: Renamed to VLSI AIO/Frontend/Backend Suite
v2.01 - 141023: Added gpdk045 PDK
v2.02 - 151023: Added newuser script for adding user
v2.05 - 241023: Patched QuartusII for Apple Silicon
v2.06 - 271023: Added VSCode (amd64), image viewer, archive viewer
v2.07 - 271023: Replace QuartusII Web edition by Subscription edition
v2.10 - 160124: Updated Vivado to 2023.2 Enterprise Edition (Artix 7 + Kintex 7)
v2.15 - 060324: Added Vitis Unified 2023.2
v2.20 - 180324: Added Cadence Xcelium, Genus, Innovus, Synopsys SpyGlass
v2.30 - 200324: Fixed uvmgen; Added Synopsys Synplify; Updated Cadence Xcelium, Genus, Virtuoso, Spectre, Mentor Calibre to newer version"

# Define the tool information
tools=("Cadence| | "
       "      Virtuoso|IC23.10.000|module load virtuoso"
       "      Spectre|23.10.063|module load spectre"
       "Mentor Calibre|2021.2_28.15|module load calibre"
       "PDKs| | "
       "      TSMC|13nm, 18nm, 65nm, 180nm| "
       "      FreePDK|15nm, 45nm| "
       "      SAED|14nm, 32nm| "
       "      GPDK|45nm| "
       "      NCSU CDK| | ")

function show_mod_info {
  TXT="\\n<span face='Monospace'>$(modinfo $1 | sed 's/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g')</span>"
  yad --title="Module information" \
      --window-icon="application-x-addon" \
      --button="yad-close" \
      --width=500 \
      --image="application-x-addon" --text="$TXT"
}
export -f show_mod_info

items=()
for tool in "${tools[@]}"; do
  IFS='|' read -r tool_name version module_command <<< "$tool"
  items+=( "$tool_name" "$version" "$module_command" )
done

# Tools tab
yad --plug=$KEY --tabnum=1 \
    --list --no-selection --column="Tool Name" --column="Version" --column="Module Command" \
    "${items[@]}" &

# Update Notes tab
sed -r "s/:[ ]*/\n/" /proc/meminfo |\
  yad --plug=$KEY --tabnum=2 \
      --list --no-selection --text="$updatenotes" &

# Main dialog
TXT="<b>Image information</b>: Debian VLSI Backend Suite ;;VERSION build ;;BUILD_NUMBER\\n"
TXT+="\\tOS: $(lsb_release -ds) on $(hostname)\\n"
;;BuiltAt
TXT+="<b>Note:</b> The container is optimized for Apple Silicon Macs.\\n"
TXT+="           You can reopen this dialog by using <b>info</b> command."

yad --notebook --window-icon="dialog-information" \
    --width=600 --height=800 --fixed --title="Image Information" --text="$TXT" --button="Thanks" \
    --key=$KEY --tab="Tools" --tab="Update Notes" --active-tab=${1:-1}
